{
    "components": {
        "green": {
            "pin": 12,
            "mode": 1
        },
        "blue": {
            "pin": 13,
            "mode": 1
        },
        "red": {
            "pin": 14,
            "mode": 1
        },
        "button": {
            "pin": 4,
            "mode": 0
        },
        "boiler": {
            "pin": 5,
            "mode": 0
        },
        "light": {
            "pin": 0,
            "mode": 2
        }
    }
}